### PR TITLE
Simplify style for lower zoom levels

### PR DESCRIPTION
**Pull request by jsanz**
This PR superseeds #4, bringing changes done there but on top of the last upstream changes from #6.

The bulk of changes affect the lower zoom levels and simplify the basemap to make it more suitable for overlaying thematic data.

Overview of changes:

- Remove the water boundaries
- Slightly darker water body labels
- Push down landuse layers to zoom 8
- Main roads are faded between zooms 6 and 8 to make them less prominent
- Main roads minzooms increased
- Towns and cities are pushed down to zoom 5
- State boundary lines style split at zoom 10
- Road shields pushed to zoom 9
- `place-country-other` layer removed

**Important**: This screenshot compare against our current production styles, were the `park` layer is still published. I'll update the screenshot when #4 is deployed.

[Preview](https://elastic.github.io/ems-basemap-editor/comparator.html?github=jsanz/osm-bright-gl-style&ref=simplify#6.2/37.583/-120.013)

image

### CODE REVIEW

**Comment by jsanz** [comment]
@nickpeihl  at https://github.com/elastic/osm-bright-gl-style/pull/4#issuecomment-925288376 you mentioned

> With the latest changes from OSM/OMT, we are seeing subdivision labels appearing at smaller scales. This is cluttering the map IMO. Perhaps we can alter the style to only show subdivision labels at larger scales.

Could you [review](https://elastic.github.io/ems-basemap-editor/comparator.html?github=jsanz/osm-bright-gl-style&ref=simplify#6.2/37.583/-120.013) if this is still the case?

[vokoscreenNG-2022-07-07_15-15-35.webm](https://user-images.githubusercontent.com/188264/177782907-25d6ed28-de69-45d9-8931-48407be4de81.webm)

Feel free to share permalinks to the previewer with the problematic areas (if any) so I can take a look.

**Review by nickpeihl — APPROVED** [review]
> Could you [review](https://elastic.github.io/ems-basemap-editor/comparator.html?github=jsanz/osm-bright-gl-style&ref=simplify#6.2/37.583/-120.013) if this is still the case?

I really like the changes. The city labels are smaller and most appear at a larger scale. [Parks are less overwhelming](https://elastic.github.io/ems-basemap-editor/comparator.html?github=jsanz/osm-bright-gl-style&ref=simplify#6.2/47.967/-121.394) which is good. [Admin boundaries](https://elastic.github.io/ems-basemap-editor/comparator.html?github=jsanz/osm-bright-gl-style&ref=simplify#10.82/-33.8507/151.1836) have changed for the better. [Water labels are a darker color](https://elastic.github.io/ems-basemap-editor/comparator.html?github=jsanz/osm-bright-gl-style&ref=simplify#5.39/41.113/13.404) so they stand out better.

**Comment by face0b1101** [comment]
Are these changes going to be an additional map style, or a direct replacement for the existing style(s)?

**Comment by jsanz** [comment]
> Are these changes going to be an additional map style, or a direct replacement for the existing style(s)?

Our current plan is to replace the existing ones with the new simplified styles. Do you foresee any issues with this?

**Comment by face0b1101** [comment]
I'm probably going to do a really bad job of explaining this, so please bear with me.

I understand how simplifying the map by removing thematic element would allow data visualisations to really _pop_, but it can be really helpful to have those thematic elements at middle and lower zoom levels for understanding the geography.

So, I'm thinking more about tracks and data points and less about large-scale aggregations - where simplifying the maps is definitely an enhancement.

I'd really like to see this the simplified map as an additional, rather than a replacement, option.

**Comment by face0b1101** [comment]
So, I'm thinking more about tracks and data points and less about large-scale aggregations - where simplifying the maps is definitely a win.

I'd really like to see this the simplified map as an additional, rather than a replacement, option.

**Comment by nickpeihl** [comment]
@face0b1101 You raise some valid points. This is no longer the default style and I (at least) consider it legacy. So maybe we shouldn't be making abrupt changes to this style? 

Of course, we've now also merged (but also not yet deployed) similar changes to the default style [here](https://github.com/elastic/osm-bright-desaturated-gl-style/pull/5). 

We've heard from users that the map styles are too busy for visualizing analytics which is why we have considered this change. But I'm also cognizant that abrupt changes can be distracting and perhaps even detrimental. Perhaps there are certain design choices we can come to an agreement on @face0b1101?

> I'd really like to see this the simplified map as an additional, rather than a replacement, option.

I'm hesitant to add more style choices for users. "[Don’t make me choose! — Designing to minimise choice"](https://medium.com/@vikigreen/don-t-make-me-choose-designing-to-minimise-choice-902c28e331ef) is a great article that explains how too many choices can be bad for user experience.

One thing we might want to consider is making these new styles only available in the next stack release rather than applying them for all past releases. Elastic Maps Service is already versioned to match the major/minor releases of the stack. Although it would require a little more behind-the-scenes work for us to deploy multiple versions of the styles.

@jsanz what do you think?

**Comment by Toojie** [comment]
I agree @face0b1101 removing particular elements in the lower zoom levels is going to have a significant for those use cases that use the geographical elements of the maps at a granular detail. The addition of this layer would be beneficial rather than replacing it. Perhaps the new proposals could be the default but in advanced settings the user/admin has the ability to revert back to these views. So we are not completely removing the capability but it is not adding to the main UI where a user is presented with multiple option?

**Comment by jsanz** [comment]
Almost two years ago we started to work on https://github.com/elastic/osm-bright-gl-style/pull/4. Back then the bright style was the default in the Elastic Maps application and concerns were raised about being too busy and crowded. We agreed on simplifying it to make it better suited for the most common use case (or at least the one we understand it's the most common).

That work was delayed and in the meantime the desaturated style [became the default](https://github.com/elastic/kibana/issues/115979) in October 21 and since then that's the default basemap for our users. This style is already less crowded even we also merged some simplifications [here](https://github.com/elastic/osm-bright-desaturated-gl-style/pull/5) as @nickpeihl already mentioned.

I agree with Nick that we shouldn't present too many styles to our users, and that we may want this change to only appear in new versions of the stack to not change current visualizations.

One more thing is that in 8.4 we are adding color blending capabilities to EMS basemaps. That makes the basemap more customizable for our users and maybe something that combined with the opacity control can be used to make the map way less prominent so we could even discard all the simplification work and just expect users to fine tune the basemap to their needs.

Peek 2022-07-25 15-12

Also something worth mentioning is that allowing users to switch off and on some predefined EMS basemap layer groups (all labels, landuse,  transportation, points of interest, etc) is something we were considering at some point.

**Pull request merged**
